version: '3.9'

services:
  backrow:
    build:
      context: .
    depends_on:
      - backrowDB
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://dev:dev@backrowDB:5432/backrow?schema=public
      - TOKEN_SECRET=suuuupersecretEncryptedToken
      - ADMIN_PASSWORD=12345

  backrowDB:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      # - ~/docker/postgres:/var/lib/postgresql/data
      #create tables
      - ./sql/backRowdb.sql/:/docker-entrypoint-initdb.d/backRowdb.sql
      - ./sql/quiz.sql/:/docker-entrypoint-initdb.d/quiz.sql
      - ./sql/tutorialSql.sql/:/docker-entrypoint-initdb.d/tutorialSql.sql
      - ./sql/user.sql/:/docker-entrypoint-initdb.d/user.sql
      - ./sql/zmap.sql/:/docker-entrypoint-initdb.d/zmap.sql

    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=backrow
