version: '3.9'

services:
  backrowDB:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=backrow
