version: '3.9'

services:
  backrowDB:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      # - ~/docker/postgres:/var/lib/postgresql/data
        #create tables
      - ./sql/backRowdb.sql/:/docker-entrypoint-initdb.d/backRowdb.sql
      - ./sql/quiz.sql/:/docker-entrypoint-initdb.d/quiz.sql
      - ./sql/tutorialSql.sql/:/docker-entrypoint-initdb.d/tutorialSql.sql
      - ./sql/zmap.sql/:/docker-entrypoint-initdb.d/zmap.sql
      
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=backrow
